apiVersion: v1
kind: Pod
metadata:
  name: not-myapp
  namespace: bpe-podname-ns
spec:
  containers:
  - command:
    - sleep
    - "300"
    image: ghcr.io/kyverno/test-busybox:1.35
    name: busybox
  - command:
    - sleep
    - "300"
    image: ghcr.io/kyverno/test-busybox:1.35
    name: busybox02
